[package]
name = "blitzr"
version = "0.2.0"
edition = "2024_07"
cairo-version = "2.11.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[dependencies]
starknet = "2.11.4"
openzeppelin_token = "1.0.0"
openzeppelin_access = "1.0.0"
openzeppelin_introspection = "1.0.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.41.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true